/* eslint-disable */
/* prettier-ignore */
/* oxlint-disable */
/* oxfmt-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const OcticonAlert24: typeof import('~icons/octicon/alert24.tsx').default
  const OcticonCheckCircle24: typeof import('~icons/octicon/check-circle24.tsx').default
  const OcticonChevronDown24: typeof import('~icons/octicon/chevron-down24.tsx').default
  const OcticonChevronRight24: typeof import('~icons/octicon/chevron-right24.tsx').default
  const OcticonCircleSlash24: typeof import('~icons/octicon/circle-slash24.tsx').default
  const OcticonInfo24: typeof import('~icons/octicon/info24.tsx').default
  const OcticonSearch24: typeof import('~icons/octicon/search24.tsx').default
  const OcticonSync24: typeof import('~icons/octicon/sync24.tsx').default
}
