name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Checkout lo-data repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          repository: laoplus/lo-data
          token: ${{ secrets.GH_PAT_CLONE_DATA_REPO }}
          path: data

      - name: Enable pnpm
        run: corepack enable

      - run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm check

      - name: Build
        run: pnpm build
